[package]
name = "reg-file-parser"
version = "0.1.0"
authors = ["Robert Cato <robertcato015@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.6"
string-builder = "0.2.0"
snafu = "0.6.10"